version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      - zip -r function.zip .

  post_build:
    commands:
      - aws lambda update-function-code \
        --function-name YOUR_LAMBDA_NAME \
        --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
